name: flutter_bugfender
description: Flutter plugin to enable Bugfender reporting (with Java and Swift support).
version: 1.0.0
author: Bugfender team <support@bugfender.com>
homepage: https://bugfender.com

flutter:
  plugin:
    androidPackage: com.ninja.flutterbugfender
    pluginClass: FlutterBugfenderPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
